# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvis.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JarvisGUI(object):
    def setupUi(self, JarvisGUI):
        JarvisGUI.setObjectName("JarvisGUI")
        JarvisGUI.resize(1174, 621)
        self.centralwidget = QtWidgets.QWidget(JarvisGUI)
        self.centralwidget.setObjectName("centralwidget")
        self.bg = QtWidgets.QLabel(self.centralwidget)
        self.bg.setGeometry(QtCore.QRect(-10, -20, 1281, 681))
        self.bg.setText("")
        self.bg.setPixmap(QtGui.QPixmap("Black_Template.jpg"))
        self.bg.setScaledContents(True)
        self.bg.setObjectName("bg")
        self.iron_man = QtWidgets.QLabel(self.centralwidget)
        self.iron_man.setGeometry(QtCore.QRect(740, 20, 471, 311))
        self.iron_man.setText("")
        self.iron_man.setPixmap(QtGui.QPixmap("Iron_Template_1.gif"))
        self.iron_man.setScaledContents(True)
        self.iron_man.setObjectName("iron_man")
        self.Voice_rec = QtWidgets.QLabel(self.centralwidget)
        self.Voice_rec.setGeometry(QtCore.QRect(-40, 100, 501, 301))
        self.Voice_rec.setText("")
        self.Voice_rec.setPixmap(QtGui.QPixmap("__1.gif"))
        self.Voice_rec.setScaledContents(True)
        self.Voice_rec.setObjectName("Voice_rec")
        self.Initialize = QtWidgets.QLabel(self.centralwidget)
        self.Initialize.setGeometry(QtCore.QRect(20, -40, 391, 201))
        self.Initialize.setText("")
        self.Initialize.setPixmap(QtGui.QPixmap("initial.gif"))
        self.Initialize.setScaledContents(True)
        self.Initialize.setObjectName("Initialize")
        self.Scan = QtWidgets.QLabel(self.centralwidget)
        self.Scan.setGeometry(QtCore.QRect(20, 410, 371, 191))
        self.Scan.setText("")
        self.Scan.setPixmap(QtGui.QPixmap("Health_Template.gif"))
        self.Scan.setScaledContents(True)
        self.Scan.setObjectName("Scan")
        self.terminal = QtWidgets.QLabel(self.centralwidget)
        self.terminal.setGeometry(QtCore.QRect(750, 360, 421, 251))
        self.terminal.setText("")
        self.terminal.setPixmap(QtGui.QPixmap("B.G_Template_1.gif"))
        self.terminal.setScaledContents(True)
        self.terminal.setObjectName("terminal")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(420, 140, 381, 211))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Earth_Template.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(470, 520, 111, 51))
        self.pushButton.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"font: 75 20pt \"Arial\";\n"
"border-radius:10px")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(600, 520, 111, 51))
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"font: 75 20pt \"Arial\";\n"
"border-radius:10px")
        self.pushButton_2.setObjectName("pushButton_2")
        self.bg.raise_()
        self.iron_man.raise_()
        self.Initialize.raise_()
        self.Scan.raise_()
        self.terminal.raise_()
        self.Voice_rec.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        JarvisGUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(JarvisGUI)
        QtCore.QMetaObject.connectSlotsByName(JarvisGUI)

    def retranslateUi(self, JarvisGUI):
        _translate = QtCore.QCoreApplication.translate
        JarvisGUI.setWindowTitle(_translate("JarvisGUI", "MainWindow"))
        self.pushButton.setText(_translate("JarvisGUI", "START"))
        self.pushButton_2.setText(_translate("JarvisGUI", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JarvisGUI = QtWidgets.QMainWindow()
    ui = Ui_JarvisGUI()
    ui.setupUi(JarvisGUI)
    JarvisGUI.show()
    sys.exit(app.exec_())
